export interface Nutrition {
  calories: number;
  protein: number;
  fat: number;
  carbs: number;
}

export interface FoodItem {
  id: string;
  name: string;
  unit: string;
  unitWeight: number;
  nutrition: Nutrition;
}

const ingredientDatabase: FoodItem[] = [
  {
    id: 'beef_sirloin',
    name: '소고기 등심',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 2.42,
      protein: 0.19,
      fat: 0.18,
      carbs: 0,
    },
  },
  {
    id: 'beef_tenderloin',
    name: '소고기 안심',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 2.18,
      protein: 0.22,
      fat: 0.13,
      carbs: 0,
    },
  },
  {
    id: 'egg',
    name: '달걀',
    unit: '개',
    unitWeight: 50,
    nutrition: {
      calories: 74,
      protein: 6.3,
      fat: 5.3,
      carbs: 0.3,
    },
  },
  {
    id: 'mackerel',
    name: '고등어',
    unit: '마리',
    unitWeight: 300,
    nutrition: {
      calories: 615,
      protein: 57,
      fat: 42,
      carbs: 0,
    },
  },
  {
    id: 'tofu',
    name: '두부',
    unit: '모',
    unitWeight: 300,
    nutrition: {
      calories: 228,
      protein: 24,
      fat: 13.5,
      carbs: 5.7,
    },
  },
  {
    id: 'garlic',
    name: '마늘',
    unit: '쪽',
    unitWeight: 5,
    nutrition: {
      calories: 7.45,
      protein: 0.315,
      fat: 0.025,
      carbs: 1.65,
    },
  },
  {
    id: 'onion',
    name: '양파',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 60,
      protein: 1.65,
      fat: 0.15,
      carbs: 13.95,
    },
  },
  {
    id: 'kimchi',
    name: '김치',
    unit: 'T',
    unitWeight: 30,
    nutrition: {
      calories: 4.5,
      protein: 0.48,
      fat: 0.09,
      carbs: 0.96,
    },
  },
  {
    id: 'doenjang',
    name: '된장',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 29.7,
      protein: 1.8,
      fat: 0.9,
      carbs: 4.05,
    },
  },
  {
    id: 'gochujang',
    name: '고추장',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 43.05,
      protein: 0.9,
      fat: 0.45,
      carbs: 9.75,
    },
  },
  {
    id: 'soy_sauce',
    name: '간장',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 7.95,
      protein: 1.2,
      fat: 0,
      carbs: 0.75,
    },
  },
  {
    id: 'apple',
    name: '사과',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 104,
      protein: 0.6,
      fat: 0.4,
      carbs: 27.6,
    },
  },

  {
    id: 'sesame_oil',
    name: '참기름',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'red_pepper_powder',
    name: '고춧가루',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 15.9,
      protein: 0.75,
      fat: 0.7,
      carbs: 2.7,
    },
  },
  {
    id: 'oyster',
    name: '굴',
    unit: '개',
    unitWeight: 20,
    nutrition: {
      calories: 13.8,
      protein: 1.8,
      fat: 0.44,
      carbs: 0.84,
    },
  },
  {
    id: 'seaweed',
    name: '김',
    unit: '장',
    unitWeight: 2.5,
    nutrition: {
      calories: 5,
      protein: 1,
      fat: 0.1,
      carbs: 0.5,
    },
  },
  {
    id: 'cucumber',
    name: '오이',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 15,
      protein: 0.7,
      fat: 0.1,
      carbs: 3.6,
    },
  },
  {
    id: 'napa_cabbage',
    name: '배추',
    unit: '포기',
    unitWeight: 2500,
    nutrition: {
      calories: 325,
      protein: 30,
      fat: 5,
      carbs: 67.5,
    },
  },
  {
    id: 'green_onion',
    name: '대파',
    unit: '대',
    unitWeight: 30,
    nutrition: {
      calories: 9.6,
      protein: 0.6,
      fat: 0.12,
      carbs: 2.1,
    },
  },
  {
    id: 'carrot',
    name: '당근',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 41,
      protein: 0.9,
      fat: 0.2,
      carbs: 9.6,
    },
  },
  {
    id: 'shrimp',
    name: '새우',
    unit: '마리',
    unitWeight: 15,
    nutrition: {
      calories: 12.75,
      protein: 2.7,
      fat: 0.15,
      carbs: 0.015,
    },
  },
  {
    id: 'radish',
    name: '무',
    unit: '개',
    unitWeight: 400,
    nutrition: {
      calories: 72,
      protein: 2.4,
      fat: 0.4,
      carbs: 16.8,
    },
  },
  {
    id: 'spinach',
    name: '시금치',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 23,
      protein: 2.9,
      fat: 0.4,
      carbs: 3.6,
    },
  },

  {
    id: 'mushroom',
    name: '버섯',
    unit: '개',
    unitWeight: 15,
    nutrition: {
      calories: 3.3,
      protein: 0.33,
      fat: 0.045,
      carbs: 0.525,
    },
  },

  {
    id: 'sweet_potato',
    name: '고구마',
    unit: '개',
    unitWeight: 180,
    nutrition: {
      calories: 162,
      protein: 1.8,
      fat: 0.36,
      carbs: 37.8,
    },
  },
  {
    id: 'potato',
    name: '감자',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 129,
      protein: 3.45,
      fat: 0.15,
      carbs: 29.4,
    },
  },
  {
    id: 'crab',
    name: '꽃게',
    unit: '마리',
    unitWeight: 200,
    nutrition: {
      calories: 174,
      protein: 36.2,
      fat: 1,
      carbs: 0,
    },
  },
  {
    id: 'pork_belly',
    name: '삼겹살',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 3.92,
      protein: 0.147,
      fat: 0.378,
      carbs: 0,
    },
  },
  {
    id: 'pork_neck',
    name: '목살',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 2.43,
      protein: 0.21,
      fat: 0.17,
      carbs: 0,
    },
  },
  {
    id: 'rice',
    name: '쌀',
    unit: '컵',
    unitWeight: 180,
    nutrition: {
      calories: 648,
      protein: 12.6,
      fat: 0.54,
      carbs: 144,
    },
  },
  {
    id: 'fish_cake',
    name: '어묵',
    unit: '장',
    unitWeight: 30,
    nutrition: {
      calories: 39,
      protein: 4.2,
      fat: 0.9,
      carbs: 4.8,
    },
  },
  {
    id: 'dumpling',
    name: '만두',
    unit: '개',
    unitWeight: 25,
    nutrition: {
      calories: 42.5,
      protein: 2.75,
      fat: 1.25,
      carbs: 5.75,
    },
  },
  {
    id: 'chicken_breast',
    name: '닭가슴살',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 330,
      protein: 62,
      fat: 7.2,
      carbs: 0,
    },
  },
  {
    id: 'spam',
    name: '스팸',
    unit: '쪽',
    unitWeight: 30,
    nutrition: {
      calories: 89.7,
      protein: 4.8,
      fat: 7.5,
      carbs: 0.9,
    },
  },
  {
    id: 'spicy_tuna_can',
    name: '고추참치',
    unit: '캔',
    unitWeight: 150,
    nutrition: {
      calories: 210,
      protein: 28,
      fat: 10,
      carbs: 2,
    },
  },
  {
    id: 'vegetable_tuna_can',
    name: '야채참치',
    unit: '캔',
    unitWeight: 150,
    nutrition: {
      calories: 195,
      protein: 26,
      fat: 8,
      carbs: 4,
    },
  },
  {
    id: 'tuna_can',
    name: '참치캔',
    unit: '캔',
    unitWeight: 150,
    nutrition: {
      calories: 198,
      protein: 42,
      fat: 1.5,
      carbs: 0,
    },
  },
  {
    id: 'squid',
    name: '오징어',
    unit: '마리',
    unitWeight: 200,
    nutrition: {
      calories: 184,
      protein: 31.2,
      fat: 2.8,
      carbs: 6.4,
    },
  },
  {
    id: 'pear',
    name: '배',
    unit: '개',
    unitWeight: 350,
    nutrition: {
      calories: 199.5,
      protein: 1.4,
      fat: 0.35,
      carbs: 53.2,
    },
  },
  {
    id: 'corn',
    name: '옥수수',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 547.5,
      protein: 13.8,
      fat: 7.35,
      carbs: 111,
    },
  },
  {
    id: 'mayo',
    name: '마요네즈',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 102,
      protein: 0.15,
      fat: 11.25,
      carbs: 0.15,
    },
  },
  {
    id: 'ketchup',
    name: '케첩',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 15.15,
      protein: 0.15,
      fat: 0.03,
      carbs: 3.9,
    },
  },
  {
    id: 'mustard',
    name: '머스터드',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 3.3,
      protein: 0.19,
      fat: 0.19,
      carbs: 0.3,
    },
  },
  {
    id: 'wasabi',
    name: '와사비',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 2.1,
      protein: 0.115,
      fat: 0.08,
      carbs: 0.335,
    },
  },
  {
    id: 'banana',
    name: '바나나',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 89,
      protein: 1.1,
      fat: 0.3,
      carbs: 22.8,
    },
  },
  {
    id: 'anchovy',
    name: '멸치',
    unit: 'T',
    unitWeight: 10,
    nutrition: {
      calories: 25.8,
      protein: 2.85,
      fat: 1.5,
      carbs: 0,
    },
  },
  {
    id: 'honey',
    name: '꿀',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 45.6,
      protein: 0.045,
      fat: 0,
      carbs: 12.3,
    },
  },
  {
    id: 'olive_oil',
    name: '올리브유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'kimchi_base',
    name: '양념김치',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 9,
      protein: 0.45,
      fat: 0.15,
      carbs: 1.95,
    },
  },
  {
    id: 'salted_shrimp',
    name: '새우젓',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 4.5,
      protein: 0.85,
      fat: 0.05,
      carbs: 0.15,
    },
  },
  {
    id: 'fish_sauce',
    name: '액젓',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 10.5,
      protein: 2.1,
      fat: 0,
      carbs: 0.45,
    },
  },
  {
    id: 'vinegar',
    name: '식초',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 2.7,
      protein: 0,
      fat: 0,
      carbs: 0.12,
    },
  },
  {
    id: 'mirin',
    name: '미림',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 25.5,
      protein: 0,
      fat: 0,
      carbs: 6.3,
    },
  },
  {
    id: 'oyster_sauce',
    name: '굴소스',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 13.8,
      protein: 0.6,
      fat: 0,
      carbs: 2.85,
    },
  },
  {
    id: 'chili_sauce',
    name: '칠리소스',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 16.8,
      protein: 0.15,
      fat: 0,
      carbs: 4.2,
    },
  },
  {
    id: 'plum_extract',
    name: '매실액',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 18,
      protein: 0.15,
      fat: 0,
      carbs: 4.5,
    },
  },
  {
    id: 'sesame_oil',
    name: '들기름',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'curry',
    name: '카레',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 48.75,
      protein: 2.1,
      fat: 2.1,
      carbs: 8.7,
    },
  },
  {
    id: 'sugar',
    name: '설탕',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 58.05,
      protein: 0,
      fat: 0,
      carbs: 15,
    },
  },
  {
    id: 'almond',
    name: '아몬드',
    unit: '알',
    unitWeight: 1.2,
    nutrition: {
      calories: 6.95,
      protein: 0.254,
      fat: 0.598,
      carbs: 0.26,
    },
  },
  {
    id: 'walnut',
    name: '호두',
    unit: '알',
    unitWeight: 2.5,
    nutrition: {
      calories: 16.35,
      protein: 0.38,
      fat: 1.63,
      carbs: 0.34,
    },
  },
  {
    id: 'peanut',
    name: '땅콩',
    unit: '알',
    unitWeight: 1,
    nutrition: {
      calories: 5.67,
      protein: 0.258,
      fat: 0.492,
      carbs: 0.16,
    },
  },
  {
    id: 'milk',
    name: '우유',
    unit: '컵',
    unitWeight: 200,
    nutrition: {
      calories: 122,
      protein: 6.6,
      fat: 6.4,
      carbs: 9.8,
    },
  },
  {
    id: 'cheese_slice',
    name: '치즈',
    unit: '장',
    unitWeight: 18,
    nutrition: {
      calories: 54,
      protein: 3.42,
      fat: 4.32,
      carbs: 0.36,
    },
  },

  {
    id: 'seaweed_dried',
    name: '마른미역',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 3.5,
      protein: 0.33,
      fat: 0.04,
      carbs: 0.75,
    },
  },

  {
    id: 'noodles',
    name: '국수',
    unit: '인분',
    unitWeight: 100,
    nutrition: {
      calories: 338,
      protein: 11,
      fat: 1.3,
      carbs: 73,
    },
  },
  {
    id: 'udon',
    name: '우동',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 694,
      protein: 17.8,
      fat: 0.8,
      carbs: 150,
    },
  },
  {
    id: 'ramen',
    name: '라면',
    unit: '개',
    unitWeight: 120,
    nutrition: {
      calories: 523.2,
      protein: 10.8,
      fat: 20.4,
      carbs: 75.6,
    },
  },
  {
    id: 'strawberry',
    name: '딸기',
    unit: '개',
    unitWeight: 15,
    nutrition: {
      calories: 4.8,
      protein: 0.105,
      fat: 0.045,
      carbs: 1.155,
    },
  },
  {
    id: 'blueberry',
    name: '블루베리',
    unit: '알',
    unitWeight: 2,
    nutrition: {
      calories: 1.14,
      protein: 0.014,
      fat: 0.006,
      carbs: 0.292,
    },
  },
  {
    id: 'quail_egg',
    name: '메추리알',
    unit: '알',
    unitWeight: 10,
    nutrition: {
      calories: 14.8,
      protein: 1.26,
      fat: 1.06,
      carbs: 0.06,
    },
  },
  {
    id: 'bread',
    name: '식빵',
    unit: '쪽',
    unitWeight: 30,
    nutrition: {
      calories: 78,
      protein: 2.7,
      fat: 1.05,
      carbs: 15,
    },
  },
  {
    id: 'bacon',
    name: '베이컨',
    unit: '쪽',
    unitWeight: 20,
    nutrition: {
      calories: 86,
      protein: 5.4,
      fat: 7.2,
      carbs: 0.24,
    },
  },
  {
    id: 'sausage',
    name: '소시지',
    unit: '개',
    unitWeight: 50,
    nutrition: {
      calories: 145,
      protein: 7.5,
      fat: 12.5,
      carbs: 1,
    },
  },
  {
    id: 'ham',
    name: '햄',
    unit: '쪽',
    unitWeight: 30,
    nutrition: {
      calories: 45,
      protein: 6.3,
      fat: 1.8,
      carbs: 0.9,
    },
  },
  {
    id: 'salted_pollack_roe',
    name: '명란젓',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 24,
      protein: 3.45,
      fat: 1.05,
      carbs: 0.75,
    },
  },
  {
    id: 'canned_corn',
    name: '옥수수캔',
    unit: '캔',
    unitWeight: 165,
    nutrition: {
      calories: 132,
      protein: 4.95,
      fat: 1.65,
      carbs: 27.06,
    },
  },
  {
    id: 'tomato_paste',
    name: '토마토페',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 13.5,
      protein: 0.66,
      fat: 0.075,
      carbs: 2.94,
    },
  },
  {
    id: 'corn_syrup',
    name: '물엿',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 45,
      protein: 0,
      fat: 0,
      carbs: 11.25,
    },
  },
  {
    id: 'starch_syrup',
    name: '물전분',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 15,
      protein: 0,
      fat: 0,
      carbs: 3.75,
    },
  },
  {
    id: 'lemon',
    name: '레몬',
    unit: '개',
    unitWeight: 85,
    nutrition: {
      calories: 24.65,
      protein: 0.935,
      fat: 0.255,
      carbs: 7.905,
    },
  },
  {
    id: 'lime',
    name: '라임',
    unit: '개',
    unitWeight: 45,
    nutrition: {
      calories: 13.5,
      protein: 0.315,
      fat: 0.09,
      carbs: 4.635,
    },
  },
  {
    id: 'tangerine',
    name: '귤',
    unit: '개',
    unitWeight: 80,
    nutrition: {
      calories: 42.4,
      protein: 0.64,
      fat: 0.16,
      carbs: 10.56,
    },
  },
  {
    id: 'bellflower_root',
    name: '도라지',
    unit: '뿌리',
    unitWeight: 30,
    nutrition: {
      calories: 22.5,
      protein: 1.5,
      fat: 0.15,
      carbs: 4.95,
    },
  },
  {
    id: 'lotus_root',
    name: '연근',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 74,
      protein: 2.6,
      fat: 0.1,
      carbs: 17.2,
    },
  },
  {
    id: 'perilla_seed',
    name: '들깨',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 85.95,
      protein: 2.655,
      fat: 7.455,
      carbs: 3.48,
    },
  },
  {
    id: 'pumpkin_seed',
    name: '호박씨',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 81.9,
      protein: 2.85,
      fat: 6.9,
      carbs: 8.1,
    },
  },
  {
    id: 'sunflower_seed',
    name: '해바라기씨',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 87.6,
      protein: 3.12,
      fat: 7.725,
      carbs: 3,
    },
  },
  {
    id: 'basil',
    name: '바질',
    unit: 'T',
    unitWeight: 5,
    nutrition: {
      calories: 1.1,
      protein: 0.115,
      fat: 0.025,
      carbs: 0.1,
    },
  },
  {
    id: 'cilantro',
    name: '고수',
    unit: '단',
    unitWeight: 30,
    nutrition: {
      calories: 7.2,
      protein: 0.72,
      fat: 0.12,
      carbs: 1.26,
    },
  },
  {
    id: 'rosemary',
    name: '로즈마리',
    unit: '줄',
    unitWeight: 5,
    nutrition: {
      calories: 1.65,
      protein: 0.018,
      fat: 0.088,
      carbs: 0.331,
    },
  },
  {
    id: 'mint',
    name: '민트',
    unit: '잎',
    unitWeight: 2,
    nutrition: {
      calories: 0.66,
      protein: 0.026,
      fat: 0.003,
      carbs: 0.024,
    },
  },
  {
    id: 'thyme',
    name: '타임',
    unit: '줄',
    unitWeight: 3,
    nutrition: {
      calories: 0.87,
      protein: 0.024,
      fat: 0.024,
      carbs: 0.06,
    },
  },
  {
    id: 'seaweed_wakame',
    name: '생미역',
    unit: '줌',
    unitWeight: 30,
    nutrition: {
      calories: 12,
      protein: 0.6,
      fat: 0.09,
      carbs: 2.82,
    },
  },
  {
    id: 'seaweed_laver',
    name: '파래',
    unit: '줌',
    unitWeight: 20,
    nutrition: {
      calories: 28,
      protein: 4.2,
      fat: 0.4,
      carbs: 3.8,
    },
  },
  {
    id: 'bamboo_shoot',
    name: '죽순',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 27,
      protein: 2.6,
      fat: 0.3,
      carbs: 5.2,
    },
  },
  {
    id: 'chestnut',
    name: '밤',
    unit: '알',
    unitWeight: 20,
    nutrition: {
      calories: 46,
      protein: 0.84,
      fat: 0.28,
      carbs: 10.4,
    },
  },
  {
    id: 'ginkgo_nut',
    name: '은행',
    unit: '알',
    unitWeight: 3,
    nutrition: {
      calories: 10.2,
      protein: 0.306,
      fat: 0.366,
      carbs: 1.674,
    },
  },
  {
    id: 'dried_seaweed',
    name: '미역줄기',
    unit: '줌',
    unitWeight: 20,
    nutrition: {
      calories: 70,
      protein: 6.6,
      fat: 0.8,
      carbs: 15,
    },
  },
  {
    id: 'bean_powder',
    name: '콩가루',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 52.5,
      protein: 3.75,
      fat: 1.95,
      carbs: 6.45,
    },
  },
  {
    id: 'rice_cake_slice',
    name: '떡볶이떡',
    unit: '개',
    unitWeight: 30,
    nutrition: {
      calories: 78,
      protein: 1.56,
      fat: 0.12,
      carbs: 17.7,
    },
  },
  {
    id: 'acorn_jelly',
    name: '도토리묵',
    unit: '쪽',
    unitWeight: 50,
    nutrition: {
      calories: 7,
      protein: 0.05,
      fat: 0.05,
      carbs: 1.7,
    },
  },
  {
    id: 'dried_radish',
    name: '무말랭이',
    unit: 'T',
    unitWeight: 10,
    nutrition: {
      calories: 23.3,
      protein: 0.8,
      fat: 0.1,
      carbs: 5.3,
    },
  },
  {
    id: 'dried_pollack',
    name: '북어',
    unit: '마리',
    unitWeight: 100,
    nutrition: {
      calories: 276,
      protein: 62.8,
      fat: 3.6,
      carbs: 0,
    },
  },
  {
    id: 'salted_mackerel',
    name: '고등어구이',
    unit: '토막',
    unitWeight: 100,
    nutrition: {
      calories: 205,
      protein: 19,
      fat: 14,
      carbs: 0,
    },
  },
  {
    id: 'crab_stick',
    name: '게맛살',
    unit: '개',
    unitWeight: 15,
    nutrition: {
      calories: 15.75,
      protein: 1.8,
      fat: 0.15,
      carbs: 2.4,
    },
  },
  {
    id: 'fish_cake_stick',
    name: '어묵봉',
    unit: '개',
    unitWeight: 25,
    nutrition: {
      calories: 32.5,
      protein: 3.5,
      fat: 0.75,
      carbs: 4,
    },
  },
  {
    id: 'quail',
    name: '메추리',
    unit: '마리',
    unitWeight: 100,
    nutrition: {
      calories: 227,
      protein: 21.3,
      fat: 15.7,
      carbs: 0,
    },
  },
  {
    id: 'duck_breast',
    name: '오리가슴살',
    unit: '쪽',
    unitWeight: 100,
    nutrition: {
      calories: 140,
      protein: 19.4,
      fat: 6.6,
      carbs: 0,
    },
  },
  {
    id: 'black_rice',
    name: '흑미',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 53.25,
      protein: 1.125,
      fat: 0.405,
      carbs: 11.55,
    },
  },
  {
    id: 'millet',
    name: '조',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 53.7,
      protein: 1.65,
      fat: 0.48,
      carbs: 10.8,
    },
  },
  {
    id: 'sorghum',
    name: '수수',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 52.5,
      protein: 1.635,
      fat: 0.495,
      carbs: 11.115,
    },
  },
  {
    id: 'sweet_rice',
    name: '찹쌀',
    unit: '컵',
    unitWeight: 180,
    nutrition: {
      calories: 642.6,
      protein: 11.7,
      fat: 0.72,
      carbs: 145.8,
    },
  },
  {
    id: 'black_bean',
    name: '서리태',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 51.75,
      protein: 3.9,
      fat: 2.25,
      carbs: 4.5,
    },
  },
  {
    id: 'red_bean',
    name: '팥',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 49.5,
      protein: 3.45,
      fat: 0.105,
      carbs: 9.75,
    },
  },
  {
    id: 'hazelnut',
    name: '헤이즐넛',
    unit: '알',
    unitWeight: 2,
    nutrition: {
      calories: 12.6,
      protein: 0.3,
      fat: 1.22,
      carbs: 0.334,
    },
  },
  {
    id: 'brazil_nut',
    name: '브라질넛',
    unit: '알',
    unitWeight: 5,
    nutrition: {
      calories: 33,
      protein: 0.725,
      fat: 3.35,
      carbs: 0.6,
    },
  },
  {
    id: 'cranberry',
    name: '크랜베리',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 46.5,
      protein: 0.045,
      fat: 0.135,
      carbs: 12.3,
    },
  },
  {
    id: 'raisin',
    name: '건포도',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 43.5,
      protein: 0.45,
      fat: 0.075,
      carbs: 11.55,
    },
  },
  {
    id: 'coconut_powder',
    name: '코코넛가루',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 93,
      protein: 0.9,
      fat: 9.3,
      carbs: 3.45,
    },
  },
  {
    id: 'lotus_leaf',
    name: '연잎',
    unit: '장',
    unitWeight: 20,
    nutrition: {
      calories: 6.2,
      protein: 0.94,
      fat: 0.16,
      carbs: 0.98,
    },
  },
  {
    id: 'crown_daisy',
    name: '쑥갓',
    unit: '단',
    unitWeight: 70,
    nutrition: {
      calories: 22.4,
      protein: 2.73,
      fat: 0.35,
      carbs: 3.85,
    },
  },
  {
    id: 'shepherd_purse',
    name: '냉이',
    unit: '단',
    unitWeight: 50,
    nutrition: {
      calories: 17,
      protein: 2.15,
      fat: 0.25,
      carbs: 2.85,
    },
  },
  {
    id: 'mugwort',
    name: '쑥',
    unit: '단',
    unitWeight: 60,
    nutrition: {
      calories: 27,
      protein: 3.12,
      fat: 0.18,
      carbs: 5.94,
    },
  },
  {
    id: 'young_radish',
    name: '열무',
    unit: '단',
    unitWeight: 150,
    nutrition: {
      calories: 25.5,
      protein: 1.65,
      fat: 0.3,
      carbs: 5.55,
    },
  },
  {
    id: 'young_pumpkin',
    name: '애호박',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 34.5,
      protein: 2.25,
      fat: 0.3,
      carbs: 7.65,
    },
  },
  {
    id: 'paprika_yellow',
    name: '노란파프리카',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 62,
      protein: 2,
      fat: 0.6,
      carbs: 12,
    },
  },
  {
    id: 'paprika_red',
    name: '빨간파프리카',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 62,
      protein: 2,
      fat: 0.6,
      carbs: 12,
    },
  },
  {
    id: 'leek',
    name: '부추',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 30,
      protein: 2.7,
      fat: 0.4,
      carbs: 5.6,
    },
  },
  {
    id: 'wild_chive',
    name: '달래',
    unit: '단',
    unitWeight: 50,
    nutrition: {
      calories: 15,
      protein: 1.35,
      fat: 0.2,
      carbs: 2.8,
    },
  },
  {
    id: 'sesame_leaves',
    name: '깻잎',
    unit: '장',
    unitWeight: 2,
    nutrition: {
      calories: 0.88,
      protein: 0.078,
      fat: 0.016,
      carbs: 0.188,
    },
  },
  {
    id: 'green_plum',
    name: '매실',
    unit: '개',
    unitWeight: 20,
    nutrition: {
      calories: 10.2,
      protein: 0.14,
      fat: 0.06,
      carbs: 2.48,
    },
  },

  {
    id: 'salted_anchovy',
    name: '멸치액젓',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 18,
      protein: 3.45,
      fat: 0.3,
      carbs: 0.6,
    },
  },
  {
    id: 'fish_cake_long',
    name: '긴어묵',
    unit: '개',
    unitWeight: 40,
    nutrition: {
      calories: 52,
      protein: 5.6,
      fat: 1.2,
      carbs: 6.4,
    },
  },
  {
    id: 'mung_bean',
    name: '녹두',
    unit: '컵',
    unitWeight: 180,
    nutrition: {
      calories: 630,
      protein: 43.2,
      fat: 3.6,
      carbs: 115.2,
    },
  },

  {
    id: 'bracken',
    name: '고사리',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 34,
      protein: 2.8,
      fat: 0.5,
      carbs: 6.4,
    },
  },
  {
    id: 'fernbrake',
    name: '취나물',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 32,
      protein: 3.1,
      fat: 0.4,
      carbs: 5.8,
    },
  },
  {
    id: 'young_green_onion',
    name: '실파',
    unit: '단',
    unitWeight: 50,
    nutrition: {
      calories: 16,
      protein: 1,
      fat: 0.2,
      carbs: 3.5,
    },
  },
  {
    id: 'perilla_sprout',
    name: '들깻잎순',
    unit: '단',
    unitWeight: 50,
    nutrition: {
      calories: 22,
      protein: 1.95,
      fat: 0.4,
      carbs: 4.7,
    },
  },
  {
    id: 'water_parsley',
    name: '미나리',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 22,
      protein: 2.1,
      fat: 0.3,
      carbs: 4.2,
    },
  },

  {
    id: 'asian_bloodwort',
    name: '돌미나리',
    unit: '단',
    unitWeight: 100,
    nutrition: {
      calories: 20,
      protein: 1.9,
      fat: 0.2,
      carbs: 4.1,
    },
  },
  {
    id: 'mulberry',
    name: '오디',
    unit: '컵',
    unitWeight: 140,
    nutrition: {
      calories: 60.2,
      protein: 2,
      fat: 0.4,
      carbs: 13.7,
    },
  },
  {
    id: 'pear_juice',
    name: '배즙',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 8.55,
      protein: 0.06,
      fat: 0.015,
      carbs: 2.28,
    },
  },
  {
    id: 'citron_tea',
    name: '유자차',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 37.5,
      protein: 0.09,
      fat: 0.03,
      carbs: 9.3,
    },
  },
  {
    id: 'ginger_juice',
    name: '생강즙',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 4,
      protein: 0.09,
      fat: 0.04,
      carbs: 0.89,
    },
  },
  {
    id: 'bokbunja',
    name: '복분자',
    unit: '컵',
    unitWeight: 150,
    nutrition: {
      calories: 85.5,
      protein: 1.5,
      fat: 0.75,
      carbs: 19.5,
    },
  },
  {
    id: 'omija',
    name: '오미자',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 9,
      protein: 0.3,
      fat: 0.15,
      carbs: 1.95,
    },
  },
  {
    id: 'soybean_sprout',
    name: '콩나물',
    unit: '봉',
    unitWeight: 250,
    nutrition: {
      calories: 75,
      protein: 7.5,
      fat: 0.5,
      carbs: 14.25,
    },
  },
  {
    id: 'mung_bean_sprout',
    name: '숙주나물',
    unit: '봉',
    unitWeight: 200,
    nutrition: {
      calories: 46,
      protein: 5,
      fat: 0.2,
      carbs: 9,
    },
  },
  {
    id: 'dried_seaweed_strip',
    name: '다시마',
    unit: '장',
    unitWeight: 10,
    nutrition: {
      calories: 35,
      protein: 3.3,
      fat: 0.4,
      carbs: 7.5,
    },
  },
  {
    id: 'dried_kelp',
    name: '미역',
    unit: '줌',
    unitWeight: 30,
    nutrition: {
      calories: 12,
      protein: 0.6,
      fat: 0.09,
      carbs: 2.82,
    },
  },
  {
    id: 'green_tea',
    name: '녹차가루',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 0,
      protein: 0.25,
      fat: 0,
      carbs: 0,
    },
  },
  {
    id: 'pine_pollen',
    name: '송화가루',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 66,
      protein: 2.85,
      fat: 1.95,
      carbs: 11.25,
    },
  },
  {
    id: 'chinese_pepper',
    name: '산초가루',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 15.5,
      protein: 0.6,
      fat: 0.45,
      carbs: 2.85,
    },
  },
  {
    id: 'cinnamon_powder',
    name: '계피가루',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 12.5,
      protein: 0.2,
      fat: 0.05,
      carbs: 3.2,
    },
  },
  {
    id: 'star_anise',
    name: '팔각',
    unit: '개',
    unitWeight: 3,
    nutrition: {
      calories: 9.6,
      protein: 0.24,
      fat: 0.45,
      carbs: 1.68,
    },
  },
  {
    id: 'lentil',
    name: '렌틸콩',
    unit: '컵',
    unitWeight: 180,
    nutrition: {
      calories: 630,
      protein: 47.7,
      fat: 3.6,
      carbs: 108,
    },
  },
  {
    id: 'chickpea',
    name: '병아리콩',
    unit: '컵',
    unitWeight: 180,
    nutrition: {
      calories: 659.7,
      protein: 34.2,
      fat: 10.8,
      carbs: 109.8,
    },
  },
  {
    id: 'enoki_mushroom',
    name: '팽이버섯',
    unit: '팩',
    unitWeight: 150,
    nutrition: {
      calories: 55.5,
      protein: 4.05,
      fat: 0.45,
      carbs: 11.7,
    },
  },
  {
    id: 'maitake_mushroom',
    name: '매이타케',
    unit: '팩',
    unitWeight: 100,
    nutrition: {
      calories: 31,
      protein: 1.9,
      fat: 0.2,
      carbs: 6.7,
    },
  },
  {
    id: 'fish_sauce',
    name: '피시소스',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 10.5,
      protein: 1.65,
      fat: 0,
      carbs: 0.75,
    },
  },
  {
    id: 'lemon_juice',
    name: '레몬즙',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 3.75,
      protein: 0.06,
      fat: 0.03,
      carbs: 1.17,
    },
  },
  {
    id: 'pomegranate_juice',
    name: '석류즙',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 12,
      protein: 0.015,
      fat: 0.045,
      carbs: 2.67,
    },
  },
  {
    id: 'kelp_powder',
    name: '다시마가루',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 52.5,
      protein: 4.95,
      fat: 0.6,
      carbs: 11.25,
    },
  },
  {
    id: 'bonito_flakes',
    name: '가쓰오부시',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 52.5,
      protein: 10.5,
      fat: 0.75,
      carbs: 0,
    },
  },
  {
    id: 'cheese_powder',
    name: '치즈가루',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 53.25,
      protein: 3.45,
      fat: 3.75,
      carbs: 2.25,
    },
  },
  {
    id: 'pickled_radish',
    name: '단무지',
    unit: '쪽',
    unitWeight: 30,
    nutrition: {
      calories: 7,
      protein: 0.24,
      fat: 0.03,
      carbs: 1.59,
    },
  },
  {
    id: 'flour',
    name: '밀가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 436.8,
      protein: 12,
      fat: 1.2,
      carbs: 91.2,
    },
  },
  {
    id: 'frying_powder',
    name: '튀김가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 429.6,
      protein: 8.4,
      fat: 1.2,
      carbs: 96,
    },
  },
  {
    id: 'bread_crumbs',
    name: '빵가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 472.8,
      protein: 16.2,
      fat: 6.48,
      carbs: 93.36,
    },
  },
  {
    id: 'starch',
    name: '전분',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 57.15,
      protein: 0.045,
      fat: 0.015,
      carbs: 13.65,
    },
  },
  {
    id: 'potato_starch',
    name: '감자전분',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 57.15,
      protein: 0.045,
      fat: 0.015,
      carbs: 13.65,
    },
  },
  {
    id: 'pancake_powder',
    name: '부침가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 427.2,
      protein: 9.6,
      fat: 1.2,
      carbs: 93.6,
    },
  },
  {
    id: 'dumpling_skin_flour',
    name: '만두피가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 436.8,
      protein: 12,
      fat: 1.2,
      carbs: 91.2,
    },
  },
  {
    id: 'rice_flour',
    name: '쌀가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 432,
      protein: 8.4,
      fat: 0.36,
      carbs: 96,
    },
  },
  {
    id: 'glutinous_rice_flour',
    name: '찹쌀가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 428.4,
      protein: 7.8,
      fat: 0.48,
      carbs: 97.2,
    },
  },
  {
    id: 'cornstarch',
    name: '옥수수전분',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 57.15,
      protein: 0.045,
      fat: 0.015,
      carbs: 13.65,
    },
  },
  {
    id: 'tapioca_starch',
    name: '타피오카전분',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 53.7,
      protein: 0.03,
      fat: 0.015,
      carbs: 13.2,
    },
  },
  {
    id: 'cake_flour',
    name: '박력분',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 432,
      protein: 9.6,
      fat: 1.2,
      carbs: 93.6,
    },
  },
  {
    id: 'bread_flour',
    name: '강력분',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 441.6,
      protein: 14.4,
      fat: 1.2,
      carbs: 88.8,
    },
  },
  {
    id: 'tempura_flour',
    name: '튀김옷가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 429.6,
      protein: 8.4,
      fat: 1.2,
      carbs: 96,
    },
  },

  {
    id: 'peach',
    name: '복숭아',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 58.5,
      protein: 1.35,
      fat: 0.45,
      carbs: 14.25,
    },
  },
  {
    id: 'watermelon',
    name: '수박',
    unit: '조각',
    unitWeight: 300,
    nutrition: {
      calories: 90,
      protein: 1.8,
      fat: 0.6,
      carbs: 22.5,
    },
  },
  {
    id: 'korean_melon',
    name: '참외',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 68,
      protein: 1.6,
      fat: 0.2,
      carbs: 17.4,
    },
  },
  {
    id: 'melon',
    name: '멜론',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 51,
      protein: 1.2,
      fat: 0.3,
      carbs: 12.75,
    },
  },
  {
    id: 'cherry',
    name: '체리',
    unit: '개',
    unitWeight: 5,
    nutrition: {
      calories: 2.5,
      protein: 0.05,
      fat: 0.015,
      carbs: 0.61,
    },
  },
  {
    id: 'pomegranate',
    name: '석류',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 124.5,
      protein: 2.55,
      fat: 1.8,
      carbs: 28.05,
    },
  },
  {
    id: 'avocado',
    name: '아보카도',
    unit: '개',
    unitWeight: 170,
    nutrition: {
      calories: 272,
      protein: 3.4,
      fat: 24.99,
      carbs: 14.45,
    },
  },
  {
    id: 'mozzarella_cheese',
    name: '모짜렐라치즈',
    unit: '장',
    unitWeight: 30,
    nutrition: {
      calories: 90,
      protein: 6.6,
      fat: 6.9,
      carbs: 0.6,
    },
  },
  {
    id: 'cheddar_cheese',
    name: '체다치즈',
    unit: '장',
    unitWeight: 30,
    nutrition: {
      calories: 114,
      protein: 7.2,
      fat: 9.3,
      carbs: 0.3,
    },
  },
  {
    id: 'cream_cheese',
    name: '크림치즈',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 49.5,
      protein: 0.87,
      fat: 4.92,
      carbs: 0.585,
    },
  },
  {
    id: 'yogurt',
    name: '요구르트',
    unit: '컵',
    unitWeight: 200,
    nutrition: {
      calories: 140,
      protein: 6.8,
      fat: 3.8,
      carbs: 22,
    },
  },
  {
    id: 'butter',
    name: '버터',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 108,
      protein: 0.12,
      fat: 12.15,
      carbs: 0,
    },
  },
  {
    id: 'whipping_cream',
    name: '생크림',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 44.1,
      protein: 0.45,
      fat: 4.5,
      carbs: 0.45,
    },
  },
  {
    id: 'heavy_cream',
    name: '휘핑크림',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 51.75,
      protein: 0.45,
      fat: 5.55,
      carbs: 0.45,
    },
  },
  {
    id: 'salt',
    name: '소금',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 0,
      protein: 0,
      fat: 0,
      carbs: 0,
    },
  },
  {
    id: 'nutmeg',
    name: '육두구',
    unit: 't',
    unitWeight: 5,
    nutrition: {
      calories: 22.25,
      protein: 0.16,
      fat: 1.54,
      carbs: 2.08,
    },
  },
  {
    id: 'bay_leaves',
    name: '월계수잎',
    unit: '장',
    unitWeight: 1,
    nutrition: {
      calories: 2.04,
      protein: 0.062,
      fat: 0.023,
      carbs: 0.417,
    },
  },

  {
    id: 'parsley',
    name: '파슬리',
    unit: 'T',
    unitWeight: 5,
    nutrition: {
      calories: 1.8,
      protein: 0.165,
      fat: 0.03,
      carbs: 0.33,
    },
  },
  {
    id: 'spaghetti',
    name: '스파게티',
    unit: '인분',
    unitWeight: 100,
    nutrition: {
      calories: 371,
      protein: 13,
      fat: 1.5,
      carbs: 75,
    },
  },
  {
    id: 'hotteok_powder',
    name: '호떡가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 438,
      protein: 9.6,
      fat: 2.4,
      carbs: 97.2,
    },
  },
  {
    id: 'castella_powder',
    name: '카스텔라가루',
    unit: '컵',
    unitWeight: 120,
    nutrition: {
      calories: 466.8,
      protein: 8.4,
      fat: 3.6,
      carbs: 102,
    },
  },
  {
    id: 'lamb',
    name: '양고기',
    unit: 'g',
    unitWeight: 1,
    nutrition: {
      calories: 2.94,
      protein: 0.25,
      fat: 0.21,
      carbs: 0,
    },
  },
  {
    id: 'smoked_duck',
    name: '훈제오리',
    unit: 'g',
    unitWeight: 50,
    nutrition: {
      calories: 3,
      protein: 0.18,
      fat: 0.25,
      carbs: 0,
    },
  },
  {
    id: 'salmon',
    name: '연어',
    unit: '조각',
    unitWeight: 100,
    nutrition: {
      calories: 208,
      protein: 22,
      fat: 13,
      carbs: 0,
    },
  },
  {
    id: 'pineapple',
    name: '파인애플',
    unit: '조각',
    unitWeight: 100,
    nutrition: {
      calories: 50,
      protein: 0.5,
      fat: 0.1,
      carbs: 13.1,
    },
  },
  {
    id: 'kiwi',
    name: '키위',
    unit: '개',
    unitWeight: 80,
    nutrition: {
      calories: 48.8,
      protein: 0.88,
      fat: 0.4,
      carbs: 11.76,
    },
  },
  {
    id: 'mango',
    name: '망고',
    unit: '개',
    unitWeight: 200,
    nutrition: {
      calories: 120,
      protein: 1.6,
      fat: 0.8,
      carbs: 30,
    },
  },
  {
    id: 'orange',
    name: '오렌지',
    unit: '개',
    unitWeight: 150,
    nutrition: {
      calories: 70.5,
      protein: 1.35,
      fat: 0.15,
      carbs: 17.7,
    },
  },
  {
    id: 'grape',
    name: '포도',
    unit: '송이',
    unitWeight: 100,
    nutrition: {
      calories: 69,
      protein: 0.7,
      fat: 0.2,
      carbs: 18.1,
    },
  },
  {
    id: 'pine_nut',
    name: '잣',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 100.95,
      protein: 2.07,
      fat: 10.245,
      carbs: 1.95,
    },
  },
  {
    id: 'pistachio',
    name: '피스타치오',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 84.3,
      protein: 3.045,
      fat: 6.87,
      carbs: 4.17,
    },
  },
  {
    id: 'sunflower_oil',
    name: '해바라기유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'canola_oil',
    name: '카놀라유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'grape_seed_oil',
    name: '포도씨유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'corn_oil',
    name: '옥수수유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'avocado_oil',
    name: '아보카도유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'peanut_oil',
    name: '땅콩유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'rice_bran_oil',
    name: '현미유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'walnut_oil',
    name: '호두유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'coconut_oil',
    name: '코코넛유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
  {
    id: 'soybean_oil',
    name: '식용유',
    unit: 'T',
    unitWeight: 15,
    nutrition: {
      calories: 132.6,
      protein: 0,
      fat: 15,
      carbs: 0,
    },
  },
];

const completedFoodDatabase: FoodItem[] = [
  {
    id: 'udon_japanese',
    name: '우동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 445,
      protein: 14,
      fat: 2,
      carbs: 92,
    },
  },
  {
    id: 'ramen_japanese',
    name: '라멘',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 485,
      protein: 16,
      fat: 16,
      carbs: 82,
    },
  },
  {
    id: 'soba',
    name: '소바',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 385,
      protein: 14,
      fat: 2,
      carbs: 78,
    },
  },
  {
    id: 'yakisoba',
    name: '야키소바',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 545,
      protein: 18,
      fat: 16,
      carbs: 85,
    },
  },
  {
    id: 'nagasaki_champon',
    name: '나가사키짬뽕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 585,
      protein: 28,
      fat: 14,
      carbs: 92,
    },
  },
  {
    id: 'katsudon',
    name: '가츠동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 24,
      carbs: 85,
    },
  },
  {
    id: 'gyudon',
    name: '규동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 645,
      protein: 34,
      fat: 22,
      carbs: 82,
    },
  },
  {
    id: 'oyakodon',
    name: '오야코동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 585,
      protein: 38,
      fat: 18,
      carbs: 78,
    },
  },
  {
    id: 'tendon',
    name: '텐동',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 725,
      protein: 24,
      fat: 28,
      carbs: 95,
    },
  },
  {
    id: 'hoedupbap',
    name: '회덮밥',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 485,
      protein: 32,
      fat: 12,
      carbs: 75,
    },
  },
  {
    id: 'salmon_dupbap',
    name: '연어덮밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 545,
      protein: 36,
      fat: 18,
      carbs: 72,
    },
  },
  {
    id: 'namasu_dupbap',
    name: '나마스덮밥',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 425,
      protein: 14,
      fat: 8,
      carbs: 78,
    },
  },
  {
    id: 'unagi_don',
    name: '우나기동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 28,
      carbs: 82,
    },
  },
  {
    id: 'tuna_sashimi',
    name: '참치회',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 242,
      protein: 48,
      fat: 6,
      carbs: 0,
    },
  },
  {
    id: 'salmon_sashimi',
    name: '연어회',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 285,
      protein: 42,
      fat: 12,
      carbs: 2,
    },
  },
  {
    id: 'flatfish_sashimi',
    name: '광어회',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 245,
      protein: 45,
      fat: 8,
      carbs: 2,
    },
  },
  {
    id: 'rockfish_sashimi',
    name: '우럭회',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 225,
      protein: 44,
      fat: 6,
      carbs: 2,
    },
  },
  {
    id: 'yellowtail_sashimi',
    name: '방어회',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 295,
      protein: 42,
      fat: 14,
      carbs: 2,
    },
  },
  {
    id: 'mixed_sashimi',
    name: '모듬회',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 325,
      protein: 52,
      fat: 12,
      carbs: 3,
    },
  },
  {
    id: 'salmon_sushi',
    name: '연어초밥',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 145,
      protein: 12,
      fat: 6,
      carbs: 24,
    },
  },
  {
    id: 'flatfish_sushi',
    name: '광어초밥',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 125,
      protein: 14,
      fat: 2,
      carbs: 24,
    },
  },
  {
    id: 'egg_sushi',
    name: '계란초밥',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 165,
      protein: 8,
      fat: 6,
      carbs: 26,
    },
  },
  {
    id: 'eel_sushi',
    name: '장어초밥',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 185,
      protein: 14,
      fat: 8,
      carbs: 24,
    },
  },
  {
    id: 'shrimp_sushi',
    name: '새우초밥',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 125,
      protein: 10,
      fat: 2,
      carbs: 24,
    },
  },
  {
    id: 'california_roll',
    name: '캘리포니아롤',
    unit: '6pcs',
    unitWeight: 180,
    nutrition: {
      calories: 345,
      protein: 12,
      fat: 14,
      carbs: 48,
    },
  },
  {
    id: 'tuna_roll',
    name: '참치롤',
    unit: '6pcs',
    unitWeight: 180,
    nutrition: {
      calories: 325,
      protein: 18,
      fat: 8,
      carbs: 46,
    },
  },
  {
    id: 'spicy_salmon_roll',
    name: '스파이시연어롤',
    unit: '6pcs',
    unitWeight: 180,
    nutrition: {
      calories: 365,
      protein: 16,
      fat: 16,
      carbs: 44,
    },
  },
  {
    id: 'flatfish_gunkanmaki',
    name: '광어군함말이',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 145,
      protein: 12,
      fat: 4,
      carbs: 22,
    },
  },
  {
    id: 'salmon_gunkanmaki',
    name: '연어군함말이',
    unit: '2pcs',
    unitWeight: 80,
    nutrition: {
      calories: 165,
      protein: 12,
      fat: 8,
      carbs: 22,
    },
  },
  {
    id: 'tonkatsu',
    name: '돈까스',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 585,
      protein: 32,
      fat: 34,
      carbs: 42,
    },
  },
  {
    id: 'cheese_tonkatsu',
    name: '치즈돈까스',
    unit: '인분',
    unitWeight: 280,
    nutrition: {
      calories: 685,
      protein: 38,
      fat: 42,
      carbs: 44,
    },
  },
  {
    id: 'hire_katsu',
    name: '히레까스',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 545,
      protein: 34,
      fat: 28,
      carbs: 42,
    },
  },
  {
    id: 'fish_katsu',
    name: '생선까스',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 28,
      fat: 24,
      carbs: 44,
    },
  },
  {
    id: 'ebi_fry',
    name: '새우튀김',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 425,
      protein: 24,
      fat: 22,
      carbs: 38,
    },
  },
  {
    id: 'yakitori',
    name: '야키토리',
    unit: '꼬치',
    unitWeight: 100,
    nutrition: {
      calories: 185,
      protein: 22,
      fat: 10,
      carbs: 4,
    },
  },
  {
    id: 'teriyaki',
    name: '데리야키',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 445,
      protein: 32,
      fat: 18,
      carbs: 42,
    },
  },
  {
    id: 'karaage',
    name: '가라아게',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 485,
      protein: 28,
      fat: 32,
      carbs: 24,
    },
  },
  {
    id: 'sake_don',
    name: '사케동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 545,
      protein: 34,
      fat: 16,
      carbs: 72,
    },
  },
  {
    id: 'okonomiyaki',
    name: '오코노미야키',
    unit: '장',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 22,
      fat: 28,
      carbs: 64,
    },
  },
  {
    id: 'takoyaki',
    name: '타코야키',
    unit: '8pcs',
    unitWeight: 160,
    nutrition: {
      calories: 385,
      protein: 14,
      fat: 16,
      carbs: 48,
    },
  },
  {
    id: 'curry_rice',
    name: '카레라이스',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 18,
      fat: 22,
      carbs: 108,
    },
  },
  {
    id: 'hamburg_steak',
    name: '함박스테이크',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 32,
      fat: 38,
      carbs: 28,
    },
  },
  {
    id: 'monaka',
    name: '모나카',
    unit: '개',
    unitWeight: 80,
    nutrition: {
      calories: 245,
      protein: 4,
      fat: 8,
      carbs: 42,
    },
  },
  {
    id: 'sukiyaki',
    name: '스키야키',
    unit: '인분',
    unitWeight: 400,
    nutrition: {
      calories: 485,
      protein: 32,
      fat: 28,
      carbs: 32,
    },
  },
  {
    id: 'shabu_shabu',
    name: '샤브샤브',
    unit: '인분',
    unitWeight: 400,
    nutrition: {
      calories: 445,
      protein: 38,
      fat: 22,
      carbs: 28,
    },
  },
  {
    id: 'dashimaki_tamago',
    name: '다시마끼타마고',
    unit: '조각',
    unitWeight: 100,
    nutrition: {
      calories: 185,
      protein: 12,
      fat: 14,
      carbs: 4,
    },
  },
  {
    id: 'odeng_tang',
    name: '어묵탕',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 245,
      protein: 18,
      fat: 8,
      carbs: 32,
    },
  },
  {
    id: 'miso_soup',
    name: '미소된장국',
    unit: '그릇',
    unitWeight: 250,
    nutrition: {
      calories: 85,
      protein: 6,
      fat: 3,
      carbs: 8,
    },
  },
  {
    id: 'agedashi_tofu',
    name: '아게다시도후',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 245,
      protein: 14,
      fat: 16,
      carbs: 18,
    },
  },
  {
    id: 'korokke',
    name: '고로케',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 285,
      protein: 8,
      fat: 14,
      carbs: 32,
    },
  },
  {
    id: 'gyoza',
    name: '교자',
    unit: '6pcs',
    unitWeight: 180,
    nutrition: {
      calories: 345,
      protein: 14,
      fat: 16,
      carbs: 42,
    },
  },
  {
    id: 'tomato_pasta',
    name: '토마토파스타',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 585,
      protein: 18,
      fat: 12,
      carbs: 102,
    },
  },
  {
    id: 'cream_pasta',
    name: '크림파스타',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 785,
      protein: 22,
      fat: 42,
      carbs: 85,
    },
  },
  {
    id: 'rose_pasta',
    name: '로제파스타',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 20,
      fat: 28,
      carbs: 92,
    },
  },
  {
    id: 'aglio_olio',
    name: '알리오올리오',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 545,
      protein: 16,
      fat: 18,
      carbs: 82,
    },
  },
  {
    id: 'vongole_pasta',
    name: '봉골레파스타',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 585,
      protein: 24,
      fat: 16,
      carbs: 88,
    },
  },
  {
    id: 'carbonara',
    name: '까르보나라',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 825,
      protein: 28,
      fat: 46,
      carbs: 82,
    },
  },
  {
    id: 'seafood_pasta',
    name: '해물파스타',
    unit: '접시',
    unitWeight: 450,
    nutrition: {
      calories: 625,
      protein: 32,
      fat: 18,
      carbs: 92,
    },
  },
  {
    id: 'arrabbiata',
    name: '아라비아타',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 565,
      protein: 18,
      fat: 14,
      carbs: 98,
    },
  },
  {
    id: 'pomodoro',
    name: '뽀모도로',
    unit: '접시',
    unitWeight: 380,
    nutrition: {
      calories: 525,
      protein: 16,
      fat: 12,
      carbs: 95,
    },
  },
  {
    id: 'meat_sauce_pasta',
    name: '미트소스파스타',
    unit: '접시',
    unitWeight: 450,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 24,
      carbs: 92,
    },
  },
  {
    id: 'pepperoni_pizza',
    name: '페퍼로니피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 385,
      protein: 16,
      fat: 18,
      carbs: 42,
    },
  },
  {
    id: 'combination_pizza',
    name: '콤비네이션피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 365,
      protein: 14,
      fat: 16,
      carbs: 44,
    },
  },
  {
    id: 'hawaiian_pizza',
    name: '하와이안피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 345,
      protein: 12,
      fat: 14,
      carbs: 46,
    },
  },
  {
    id: 'cheese_pizza',
    name: '치즈피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 355,
      protein: 14,
      fat: 16,
      carbs: 42,
    },
  },
  {
    id: 'potato_pizza',
    name: '포테이토피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 375,
      protein: 12,
      fat: 16,
      carbs: 48,
    },
  },
  {
    id: 'margherita_pizza',
    name: '마르게리타피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 325,
      protein: 12,
      fat: 14,
      carbs: 42,
    },
  },
  {
    id: 'sweet_potato_pizza',
    name: '고구마피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 365,
      protein: 12,
      fat: 15,
      carbs: 48,
    },
  },
  {
    id: 'seafood_pizza',
    name: '시푸드피자',
    unit: '조각',
    unitWeight: 150,
    nutrition: {
      calories: 345,
      protein: 16,
      fat: 14,
      carbs: 42,
    },
  },
  {
    id: 'ribeye_steak',
    name: '립아이스테이크',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 785,
      protein: 62,
      fat: 58,
      carbs: 2,
    },
  },
  {
    id: 'tbone_steak',
    name: '티본스테이크',
    unit: '인분',
    unitWeight: 350,
    nutrition: {
      calories: 845,
      protein: 68,
      fat: 62,
      carbs: 2,
    },
  },
  {
    id: 'tenderloin_steak',
    name: '안심스테이크',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 585,
      protein: 58,
      fat: 38,
      carbs: 2,
    },
  },
  {
    id: 'sirloin_steak',
    name: '등심스테이크',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 685,
      protein: 62,
      fat: 46,
      carbs: 2,
    },
  },
  {
    id: 'pork_ribs',
    name: '폭립',
    unit: '인분',
    unitWeight: 400,
    nutrition: {
      calories: 885,
      protein: 58,
      fat: 68,
      carbs: 12,
    },
  },
  {
    id: 'bbq_ribs',
    name: '바비큐립',
    unit: '인분',
    unitWeight: 400,
    nutrition: {
      calories: 865,
      protein: 56,
      fat: 64,
      carbs: 18,
    },
  },
  {
    id: 'chicken_steak',
    name: '치킨스테이크',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 52,
      fat: 28,
      carbs: 4,
    },
  },
  {
    id: 'hamburg_steak',
    name: '함박스테이크',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 42,
      fat: 38,
      carbs: 22,
    },
  },
  {
    id: 'caesar_salad',
    name: '시저샐러드',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 285,
      protein: 12,
      fat: 22,
      carbs: 12,
    },
  },
  {
    id: 'greek_salad',
    name: '그리스샐러드',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 265,
      protein: 8,
      fat: 22,
      carbs: 12,
    },
  },
  {
    id: 'waldorf_salad',
    name: '월도프샐러드',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 285,
      protein: 6,
      fat: 20,
      carbs: 24,
    },
  },
  {
    id: 'quinoa_salad',
    name: '퀴노아샐러드',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 245,
      protein: 8,
      fat: 12,
      carbs: 32,
    },
  },
  {
    id: 'caprese_salad',
    name: '카프레제샐러드',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 225,
      protein: 12,
      fat: 16,
      carbs: 8,
    },
  },
  {
    id: 'nicoise_salad',
    name: '니수아즈샐러드',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 295,
      protein: 18,
      fat: 18,
      carbs: 16,
    },
  },
  {
    id: 'pasta_salad',
    name: '파스타샐러드',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 345,
      protein: 10,
      fat: 14,
      carbs: 48,
    },
  },
  {
    id: 'chickpea_salad',
    name: '병아리콩샐러드',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 265,
      protein: 12,
      fat: 12,
      carbs: 32,
    },
  },
  {
    id: 'garden_salad',
    name: '가든샐러드',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 125,
      protein: 4,
      fat: 6,
      carbs: 16,
    },
  },
  {
    id: 'cobb_salad',
    name: '콥샐러드',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 345,
      protein: 24,
      fat: 24,
      carbs: 14,
    },
  },
  {
    id: 'ricotta_salad',
    name: '리코타치즈샐러드',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 265,
      protein: 14,
      fat: 18,
      carbs: 12,
    },
  },
  {
    id: 'chicken_breast_salad',
    name: '닭가슴살샐러드',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 285,
      protein: 32,
      fat: 14,
      carbs: 12,
    },
  },
  {
    id: 'mushroom_soup',
    name: '양송이스프',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 185,
      protein: 6,
      fat: 12,
      carbs: 16,
    },
  },
  {
    id: 'corn_cream_soup',
    name: '콘크림스프',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 245,
      protein: 8,
      fat: 14,
      carbs: 28,
    },
  },
  {
    id: 'tomato_soup',
    name: '토마토스프',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 165,
      protein: 4,
      fat: 8,
      carbs: 22,
    },
  },
  {
    id: 'onion_soup',
    name: '양파스프',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 145,
      protein: 4,
      fat: 6,
      carbs: 20,
    },
  },
  {
    id: 'hamburger',
    name: '햄버거',
    unit: '개',
    unitWeight: 250,
    nutrition: {
      calories: 545,
      protein: 28,
      fat: 32,
      carbs: 42,
    },
  },
  {
    id: 'cheeseburger',
    name: '치즈버거',
    unit: '개',
    unitWeight: 270,
    nutrition: {
      calories: 585,
      protein: 32,
      fat: 36,
      carbs: 42,
    },
  },
  {
    id: 'bacon_burger',
    name: '베이컨버거',
    unit: '개',
    unitWeight: 280,
    nutrition: {
      calories: 625,
      protein: 34,
      fat: 38,
      carbs: 44,
    },
  },
  {
    id: 'blt_sandwich',
    name: 'BLT샌드위치',
    unit: '개',
    unitWeight: 220,
    nutrition: {
      calories: 485,
      protein: 22,
      fat: 28,
      carbs: 38,
    },
  },
  {
    id: 'club_sandwich',
    name: '클럽샌드위치',
    unit: '개',
    unitWeight: 250,
    nutrition: {
      calories: 545,
      protein: 28,
      fat: 32,
      carbs: 42,
    },
  },
  {
    id: 'chicken_burger',
    name: '치킨버거',
    unit: '개',
    unitWeight: 250,
    nutrition: {
      calories: 525,
      protein: 26,
      fat: 28,
      carbs: 44,
    },
  },
  {
    id: 'shrimp_burger',
    name: '새우버거',
    unit: '개',
    unitWeight: 230,
    nutrition: {
      calories: 485,
      protein: 22,
      fat: 24,
      carbs: 46,
    },
  },
  {
    id: 'risotto',
    name: '리조또',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 585,
      protein: 18,
      fat: 22,
      carbs: 85,
    },
  },
  {
    id: 'omelette',
    name: '오믈렛',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 385,
      protein: 22,
      fat: 26,
      carbs: 18,
    },
  },
  {
    id: 'fish_and_chips',
    name: '피쉬앤칩스',
    unit: '접시',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 38,
      carbs: 62,
    },
  },
  {
    id: 'gratin',
    name: '그라탕',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 585,
      protein: 24,
      fat: 32,
      carbs: 52,
    },
  },
  {
    id: 'steak_donburi',
    name: '스테이크덮밥',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 785,
      protein: 42,
      fat: 34,
      carbs: 85,
    },
  },
  {
    id: 'chicken_cutlet',
    name: '치킨커틀렛',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 545,
      protein: 38,
      fat: 28,
      carbs: 42,
    },
  },
  {
    id: 'pork_cutlet',
    name: '포크커틀렛',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 36,
      fat: 32,
      carbs: 44,
    },
  },
  {
    id: 'french_fries',
    name: '감자튀김',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 385,
      protein: 4,
      fat: 18,
      carbs: 52,
    },
  },
  {
    id: 'potato_wedges',
    name: '웨지감자',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 345,
      protein: 4,
      fat: 14,
      carbs: 54,
    },
  },

  {
    id: 'jjajangmyeon',
    name: '짜장면',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 785,
      protein: 24,
      fat: 18,
      carbs: 142,
    },
  },
  {
    id: 'jjamppong',
    name: '짬뽕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 645,
      protein: 32,
      fat: 15,
      carbs: 108,
    },
  },
  {
    id: 'udong',
    name: '우동',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 485,
      protein: 16,
      fat: 4,
      carbs: 98,
    },
  },
  {
    id: 'ulMyeon',
    name: '울면',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 525,
      protein: 18,
      fat: 8,
      carbs: 102,
    },
  },
  {
    id: 'chinese_naengmyeon',
    name: '중국냉면',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 495,
      protein: 16,
      fat: 6,
      carbs: 98,
    },
  },
  {
    id: 'samson_jjajang',
    name: '삼선짜장',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 845,
      protein: 32,
      fat: 22,
      carbs: 144,
    },
  },
  {
    id: 'samson_jjamppong',
    name: '삼선짬뽕',
    unit: '그릇',
    unitWeight: 550,
    nutrition: {
      calories: 685,
      protein: 38,
      fat: 18,
      carbs: 110,
    },
  },
  {
    id: 'bokkeumbap',
    name: '볶음밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 585,
      protein: 16,
      fat: 14,
      carbs: 102,
    },
  },
  {
    id: 'shrimp_bokkeumbap',
    name: '새우볶음밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 625,
      protein: 22,
      fat: 16,
      carbs: 102,
    },
  },
  {
    id: 'japchae_bap',
    name: '잡채밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 595,
      protein: 14,
      fat: 12,
      carbs: 108,
    },
  },
  {
    id: 'mapadubu_bap',
    name: '마파두부밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 545,
      protein: 24,
      fat: 16,
      carbs: 85,
    },
  },
  {
    id: 'samson_bokkeumbap',
    name: '삼선볶음밥',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 645,
      protein: 28,
      fat: 18,
      carbs: 98,
    },
  },
  {
    id: 'egg_soup',
    name: '계란국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 125,
      protein: 8,
      fat: 6,
      carbs: 8,
    },
  },
  {
    id: 'corn_soup',
    name: '옥수수국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 185,
      protein: 6,
      fat: 4,
      carbs: 38,
    },
  },
  {
    id: 'sanlartang',
    name: '산라탕',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 345,
      protein: 24,
      fat: 18,
      carbs: 28,
    },
  },
  {
    id: 'yang_jjamppong',
    name: '양짬뽕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 685,
      protein: 36,
      fat: 18,
      carbs: 102,
    },
  },
  {
    id: 'wooyuk_tangmyeon',
    name: '우육탕면',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 585,
      protein: 32,
      fat: 16,
      carbs: 95,
    },
  },
  {
    id: 'hureuruk_guksu',
    name: '후루룩국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 445,
      protein: 14,
      fat: 6,
      carbs: 88,
    },
  },
  {
    id: 'tangsuyuk',
    name: '탕수육',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 42,
      carbs: 52,
    },
  },
  {
    id: 'kkanpunggi',
    name: '깐풍기',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 645,
      protein: 38,
      fat: 38,
      carbs: 42,
    },
  },
  {
    id: 'lajogi',
    name: '라조기',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 625,
      protein: 36,
      fat: 36,
      carbs: 44,
    },
  },
  {
    id: 'yuringi',
    name: '유린기',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 42,
      fat: 32,
      carbs: 38,
    },
  },
  {
    id: 'kkanshao_shrimp',
    name: '깐쇼새우',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 32,
      fat: 28,
      carbs: 36,
    },
  },
  {
    id: 'chili_shrimp',
    name: '칠리새우',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 465,
      protein: 34,
      fat: 26,
      carbs: 32,
    },
  },
  {
    id: 'yangjangpi',
    name: '양장피',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 345,
      protein: 18,
      fat: 12,
      carbs: 48,
    },
  },
  {
    id: 'gochu_japchae',
    name: '고추잡채',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 385,
      protein: 16,
      fat: 14,
      carbs: 56,
    },
  },
  {
    id: 'palbochae',
    name: '팔보채',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 445,
      protein: 28,
      fat: 18,
      carbs: 52,
    },
  },
  {
    id: 'mapadubu',
    name: '마파두부',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 385,
      protein: 24,
      fat: 22,
      carbs: 28,
    },
  },
  {
    id: 'eohyang_yuksul',
    name: '어향육슬',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 445,
      protein: 32,
      fat: 26,
      carbs: 32,
    },
  },
  {
    id: 'dongpayuk',
    name: '동파육',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 685,
      protein: 34,
      fat: 52,
      carbs: 18,
    },
  },
  {
    id: 'yusansul',
    name: '유산슬',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 425,
      protein: 32,
      fat: 24,
      carbs: 28,
    },
  },
  {
    id: 'yangkkochi',
    name: '양꼬치',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 36,
      fat: 32,
      carbs: 12,
    },
  },
  {
    id: 'rajoyuk',
    name: '라조육',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 585,
      protein: 32,
      fat: 38,
      carbs: 34,
    },
  },
  {
    id: 'kkanpung_shrimp',
    name: '깐풍새우',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 445,
      protein: 34,
      fat: 26,
      carbs: 28,
    },
  },
  {
    id: 'gguabarou',
    name: '꿔바로우',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 625,
      protein: 28,
      fat: 42,
      carbs: 44,
    },
  },
  {
    id: 'spring_rolls',
    name: '춘권',
    unit: '개',
    unitWeight: 80,
    nutrition: {
      calories: 185,
      protein: 6,
      fat: 8,
      carbs: 24,
    },
  },
  {
    id: 'menbosha',
    name: '멘보샤',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 245,
      protein: 12,
      fat: 16,
      carbs: 18,
    },
  },
  {
    id: 'kkanpung_jungsae',
    name: '깐풍중새우',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 465,
      protein: 36,
      fat: 28,
      carbs: 26,
    },
  },
  {
    id: 'pimang_pork',
    name: '피망돼지고기',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 425,
      protein: 28,
      fat: 26,
      carbs: 24,
    },
  },
  {
    id: 'egg_tomato',
    name: '계란토마토볶음',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 285,
      protein: 16,
      fat: 18,
      carbs: 18,
    },
  },
  {
    id: 'garlic_pork',
    name: '마늘쫑 돼지고기볶음',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 445,
      protein: 32,
      fat: 28,
      carbs: 22,
    },
  },
  {
    id: 'gochu_japchae_bap',
    name: '고추잡채밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 585,
      protein: 22,
      fat: 14,
      carbs: 98,
    },
  },
  {
    id: 'gun_mandu',
    name: '군만두',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 485,
      protein: 16,
      fat: 22,
      carbs: 58,
    },
  },
  {
    id: 'mul_mandu',
    name: '물만두',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 385,
      protein: 14,
      fat: 8,
      carbs: 68,
    },
  },
  {
    id: 'dimsum',
    name: '딤섬',
    unit: '개',
    unitWeight: 50,
    nutrition: {
      calories: 125,
      protein: 6,
      fat: 4,
      carbs: 16,
    },
  },
  {
    id: 'soryongpo',
    name: '소룡포',
    unit: '개',
    unitWeight: 40,
    nutrition: {
      calories: 85,
      protein: 5,
      fat: 3,
      carbs: 12,
    },
  },
  {
    id: 'shaomai',
    name: '샤오마이',
    unit: '개',
    unitWeight: 45,
    nutrition: {
      calories: 95,
      protein: 6,
      fat: 4,
      carbs: 10,
    },
  },
  {
    id: 'broccoli_bokeum',
    name: '브로콜리볶음',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 145,
      protein: 8,
      fat: 6,
      carbs: 16,
    },
  },
  {
    id: 'cheonggyeongchae_bokeum',
    name: '청경채볶음',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 125,
      protein: 6,
      fat: 5,
      carbs: 14,
    },
  },

  {
    id: 'nanjawan',
    name: '난자완스',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 28,
      fat: 32,
      carbs: 24,
    },
  },

  {
    id: 'kimchi_baechu',
    name: '배추김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 25,
      protein: 2.5,
      fat: 0.5,
      carbs: 4.5,
    },
  },
  {
    id: 'bibimbap',
    name: '비빔밥',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 580,
      protein: 18,
      fat: 12,
      carbs: 95,
    },
  },
  {
    id: 'kimchi_stew',
    name: '김치찌개',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 285,
      protein: 19,
      fat: 16,
      carbs: 15,
    },
  },
  {
    id: 'beef_bulgogi',
    name: '불고기',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 450,
      protein: 35,
      fat: 27,
      carbs: 18,
    },
  },
  {
    id: 'samgyeopsal',
    name: '삼겹살',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 784,
      protein: 29.4,
      fat: 75.6,
      carbs: 0,
    },
  },
  {
    id: 'doenjang_stew',
    name: '된장찌개',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 195,
      protein: 15,
      fat: 9,
      carbs: 16,
    },
  },
  {
    id: 'japchae',
    name: '잡채',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 385,
      protein: 10,
      fat: 14,
      carbs: 55,
    },
  },
  {
    id: 'seolleongtang',
    name: '설렁탕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 355,
      protein: 28,
      fat: 24,
      carbs: 8,
    },
  },
  {
    id: 'tteokbokki',
    name: '떡볶이',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 490,
      protein: 12,
      fat: 8,
      carbs: 92,
    },
  },
  {
    id: 'samgyetang',
    name: '삼계탕',
    unit: '그릇',
    unitWeight: 800,
    nutrition: {
      calories: 420,
      protein: 45,
      fat: 18,
      carbs: 24,
    },
  },
  {
    id: 'mul_naengmyeon',
    name: '물냉면',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 425,
      protein: 15,
      fat: 3,
      carbs: 88,
    },
  },
  {
    id: 'galbitang',
    name: '갈비탕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 465,
      protein: 38,
      fat: 28,
      carbs: 16,
    },
  },
  {
    id: 'jeyuk_bokkeum',
    name: '제육볶음',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 485,
      protein: 32,
      fat: 34,
      carbs: 12,
    },
  },
  {
    id: 'haemul_pajeon',
    name: '해물파전',
    unit: '접시',
    unitWeight: 350,
    nutrition: {
      calories: 545,
      protein: 18,
      fat: 22,
      carbs: 72,
    },
  },
  {
    id: 'dakgalbi',
    name: '닭갈비',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 425,
      protein: 38,
      fat: 22,
      carbs: 24,
    },
  },
  {
    id: 'sundubu_jjigae',
    name: '순두부찌개',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 245,
      protein: 18,
      fat: 14,
      carbs: 12,
    },
  },
  {
    id: 'gimbap',
    name: '김밥',
    unit: '줄',
    unitWeight: 250,
    nutrition: {
      calories: 460,
      protein: 15,
      fat: 8,
      carbs: 85,
    },
  },
  {
    id: 'kimchi_bokkeumbap',
    name: '김치볶음밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 525,
      protein: 16,
      fat: 12,
      carbs: 92,
    },
  },
  {
    id: 'miyeokguk',
    name: '미역국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 145,
      protein: 12,
      fat: 6,
      carbs: 14,
    },
  },
  {
    id: 'kongnamul_guk',
    name: '콩나물국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 85,
      protein: 6,
      fat: 2,
      carbs: 12,
    },
  },
  {
    id: 'kkongchi_jorim',
    name: '갈치조림',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 325,
      protein: 42,
      fat: 14,
      carbs: 8,
    },
  },
  {
    id: 'jangjorim',
    name: '장조림',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 245,
      protein: 28,
      fat: 12,
      carbs: 6,
    },
  },
  {
    id: 'dolsot_bibimbap',
    name: '돌솥비빔밥',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 625,
      protein: 22,
      fat: 14,
      carbs: 105,
    },
  },
  {
    id: 'budae_jjigae',
    name: '부대찌개',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 485,
      protein: 28,
      fat: 32,
      carbs: 22,
    },
  },
  {
    id: 'kalguksu',
    name: '칼국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 445,
      protein: 16,
      fat: 4,
      carbs: 88,
    },
  },
  {
    id: 'ojingeo_bokkeum',
    name: '오징어볶음',
    unit: '접시',
    unitWeight: 250,
    nutrition: {
      calories: 285,
      protein: 32,
      fat: 8,
      carbs: 24,
    },
  },

  {
    id: 'sundae',
    name: '순대',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 385,
      protein: 18,
      fat: 14,
      carbs: 52,
    },
  },
  {
    id: 'kongnamul_muchim',
    name: '콩나물무침',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 85,
      protein: 6,
      fat: 4,
      carbs: 8,
    },
  },
  {
    id: 'kimchijeon',
    name: '김치전',
    unit: '장',
    unitWeight: 200,
    nutrition: {
      calories: 325,
      protein: 8,
      fat: 12,
      carbs: 48,
    },
  },
  {
    id: 'doenjang_guk',
    name: '된장국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 105,
      protein: 8,
      fat: 4,
      carbs: 12,
    },
  },
  {
    id: 'beef_galbi',
    name: '소갈비구이',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 645,
      protein: 48,
      fat: 45,
      carbs: 12,
    },
  },
  {
    id: 'pork_galbi',
    name: '돼지갈비구이',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 720,
      protein: 42,
      fat: 54,
      carbs: 15,
    },
  },
  {
    id: 'galbi_jjim',
    name: '갈비찜',
    unit: '인분',
    unitWeight: 350,
    nutrition: {
      calories: 585,
      protein: 45,
      fat: 38,
      carbs: 22,
    },
  },
  {
    id: 'LA_galbi',
    name: 'LA갈비',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 595,
      protein: 42,
      fat: 42,
      carbs: 14,
    },
  },
  {
    id: 'moksal_gui',
    name: '목살구이',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 486,
      protein: 42,
      fat: 34,
      carbs: 0,
    },
  },
  {
    id: 'gyeran_guk',
    name: '계란국',
    unit: '그릇',
    unitWeight: 250,
    nutrition: {
      calories: 125,
      protein: 8,
      fat: 8,
      carbs: 4,
    },
  },
  {
    id: 'kimchi_guk',
    name: '김치국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 65,
      protein: 4,
      fat: 2,
      carbs: 8,
    },
  },
  {
    id: 'mu_guk',
    name: '무국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 85,
      protein: 6,
      fat: 3,
      carbs: 10,
    },
  },
  {
    id: 'siraegi_guk',
    name: '시래기국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 95,
      protein: 7,
      fat: 4,
      carbs: 12,
    },
  },
  {
    id: 'bugeot_guk',
    name: '북엇국',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 145,
      protein: 22,
      fat: 4,
      carbs: 8,
    },
  },
  {
    id: 'haejang_guk',
    name: '해장국',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 345,
      protein: 28,
      fat: 18,
      carbs: 16,
    },
  },
  {
    id: 'bibim_naengmyeon',
    name: '비빔냉면',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 485,
      protein: 18,
      fat: 8,
      carbs: 92,
    },
  },
  {
    id: 'milmyeon',
    name: '밀면',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 445,
      protein: 16,
      fat: 6,
      carbs: 85,
    },
  },
  {
    id: 'jjolmyeon',
    name: '쫄면',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 465,
      protein: 15,
      fat: 8,
      carbs: 88,
    },
  },
  {
    id: 'kongguksu',
    name: '콩국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 385,
      protein: 22,
      fat: 12,
      carbs: 58,
    },
  },
  {
    id: 'sujebi',
    name: '수제비',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 425,
      protein: 14,
      fat: 4,
      carbs: 82,
    },
  },
  {
    id: 'rabokki',
    name: '라볶이',
    unit: '인분',
    unitWeight: 350,
    nutrition: {
      calories: 545,
      protein: 16,
      fat: 12,
      carbs: 98,
    },
  },
  {
    id: 'eomuk',
    name: '어묵',
    unit: '인분',
    unitWeight: 150,
    nutrition: {
      calories: 195,
      protein: 21,
      fat: 4.5,
      carbs: 24,
    },
  },
  {
    id: 'tteok_kkochi',
    name: '떡꼬치',
    unit: '개',
    unitWeight: 100,
    nutrition: {
      calories: 225,
      protein: 4,
      fat: 6,
      carbs: 42,
    },
  },
  {
    id: 'mandu',
    name: '만두',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 340,
      protein: 22,
      fat: 10,
      carbs: 48,
    },
  },
  {
    id: 'gonggi_bap',
    name: '공기밥',
    unit: '공기',
    unitWeight: 210,
    nutrition: {
      calories: 310,
      protein: 6,
      fat: 0.5,
      carbs: 68,
    },
  },
  {
    id: 'dolsot_bap',
    name: '돌솥밥',
    unit: '그릇',
    unitWeight: 250,
    nutrition: {
      calories: 345,
      protein: 7,
      fat: 1,
      carbs: 75,
    },
  },
  {
    id: 'kong_bap',
    name: '콩밥',
    unit: '공기',
    unitWeight: 220,
    nutrition: {
      calories: 325,
      protein: 9,
      fat: 2,
      carbs: 70,
    },
  },
  {
    id: 'heukmi_bap',
    name: '흑미밥',
    unit: '공기',
    unitWeight: 210,
    nutrition: {
      calories: 315,
      protein: 7,
      fat: 1,
      carbs: 69,
    },
  },
  {
    id: 'japgok_bap',
    name: '잡곡밥',
    unit: '공기',
    unitWeight: 220,
    nutrition: {
      calories: 320,
      protein: 8,
      fat: 2,
      carbs: 67,
    },
  },
  {
    id: 'hyeonmi_bap',
    name: '현미밥',
    unit: '공기',
    unitWeight: 210,
    nutrition: {
      calories: 305,
      protein: 7,
      fat: 2.5,
      carbs: 65,
    },
  },
  {
    id: 'jumuk_bap',
    name: '주먹밥',
    unit: '개',
    unitWeight: 130,
    nutrition: {
      calories: 185,
      protein: 4,
      fat: 2,
      carbs: 40,
    },
  },
  {
    id: 'yangnyeom_galbi',
    name: '양념갈비',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 685,
      protein: 45,
      fat: 48,
      carbs: 22,
    },
  },
  {
    id: 'saeng_galbi',
    name: '생갈비',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 625,
      protein: 48,
      fat: 42,
      carbs: 8,
    },
  },

  {
    id: 'dosirak_bap',
    name: '즉석밥',
    unit: '개',
    unitWeight: 210,
    nutrition: {
      calories: 300,
      protein: 5,
      fat: 0.5,
      carbs: 66,
    },
  },
  {
    id: 'total_kimchi',
    name: '총각김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 28,
      protein: 2,
      fat: 0.4,
      carbs: 5,
    },
  },
  {
    id: 'gat_kimchi',
    name: '갓김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 25,
      protein: 2.2,
      fat: 0.3,
      carbs: 4.8,
    },
  },
  {
    id: 'baek_kimchi',
    name: '백김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 22,
      protein: 1.8,
      fat: 0.2,
      carbs: 4.5,
    },
  },
  {
    id: 'yeolmu_kimchi',
    name: '열무김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 24,
      protein: 2,
      fat: 0.3,
      carbs: 4.6,
    },
  },
  {
    id: 'kkakdugi',
    name: '깍두기',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 26,
      protein: 2.1,
      fat: 0.4,
      carbs: 4.8,
    },
  },
  {
    id: 'oiji_sobagi',
    name: '오이소박이',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 20,
      protein: 1.5,
      fat: 0.2,
      carbs: 4,
    },
  },
  {
    id: 'pa_kimchi',
    name: '파김치',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 25,
      protein: 2,
      fat: 0.3,
      carbs: 4.7,
    },
  },
  {
    id: 'dongchimi',
    name: '동치미',
    unit: '공기',
    unitWeight: 100,
    nutrition: {
      calories: 15,
      protein: 1,
      fat: 0.1,
      carbs: 3.5,
    },
  },
  {
    id: 'myeongran_jeot',
    name: '명란젓',
    unit: '숟가락',
    unitWeight: 15,
    nutrition: {
      calories: 24,
      protein: 3.45,
      fat: 1.05,
      carbs: 0.75,
    },
  },
  {
    id: 'changran_jeot',
    name: '창란젓',
    unit: '숟가락',
    unitWeight: 15,
    nutrition: {
      calories: 22,
      protein: 3.2,
      fat: 0.9,
      carbs: 0.8,
    },
  },
  {
    id: 'ojingeo_jeot',
    name: '오징어젓',
    unit: '숟가락',
    unitWeight: 15,
    nutrition: {
      calories: 20,
      protein: 3,
      fat: 0.8,
      carbs: 0.7,
    },
  },
  {
    id: 'nakji_jeot',
    name: '낙지젓',
    unit: '숟가락',
    unitWeight: 15,
    nutrition: {
      calories: 19,
      protein: 2.8,
      fat: 0.7,
      carbs: 0.8,
    },
  },
  {
    id: 'jogae_jeot',
    name: '조개젓',
    unit: '숟가락',
    unitWeight: 15,
    nutrition: {
      calories: 18,
      protein: 2.6,
      fat: 0.6,
      carbs: 0.9,
    },
  },
  {
    id: 'gamjatang',
    name: '감자탕',
    unit: '그릇',
    unitWeight: 500,
    nutrition: {
      calories: 485,
      protein: 32,
      fat: 28,
      carbs: 25,
    },
  },
  {
    id: 'chueotang',
    name: '추어탕',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 345,
      protein: 28,
      fat: 16,
      carbs: 18,
    },
  },
  {
    id: 'gamja_jeon',
    name: '감자전',
    unit: '장',
    unitWeight: 150,
    nutrition: {
      calories: 285,
      protein: 6,
      fat: 12,
      carbs: 38,
    },
  },
  {
    id: 'bindaetteok',
    name: '빈대떡',
    unit: '장',
    unitWeight: 150,
    nutrition: {
      calories: 320,
      protein: 12,
      fat: 14,
      carbs: 42,
    },
  },
  {
    id: 'gochu_jeon',
    name: '고추전',
    unit: '접시',
    unitWeight: 120,
    nutrition: {
      calories: 225,
      protein: 5,
      fat: 12,
      carbs: 24,
    },
  },
  {
    id: 'dubu_jeon',
    name: '두부전',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 245,
      protein: 16,
      fat: 14,
      carbs: 15,
    },
  },
  {
    id: 'yachae_jeon',
    name: '야채전',
    unit: '장',
    unitWeight: 150,
    nutrition: {
      calories: 265,
      protein: 6,
      fat: 14,
      carbs: 28,
    },
  },
  {
    id: 'dongtae_jeon',
    name: '동태전',
    unit: '장',
    unitWeight: 150,
    nutrition: {
      calories: 285,
      protein: 22,
      fat: 16,
      carbs: 14,
    },
  },
  {
    id: 'doraji_namul',
    name: '도라지나물',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 75,
      protein: 2,
      fat: 3,
      carbs: 12,
    },
  },
  {
    id: 'gosari_namul',
    name: '고사리나물',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 85,
      protein: 3,
      fat: 4,
      carbs: 10,
    },
  },
  {
    id: 'chwi_namul',
    name: '취나물',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 65,
      protein: 3,
      fat: 2,
      carbs: 8,
    },
  },
  {
    id: 'sigeumchi_namul',
    name: '시금치나물',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 55,
      protein: 3,
      fat: 2,
      carbs: 6,
    },
  },
  {
    id: 'oi_muchim',
    name: '오이무침',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 45,
      protein: 1,
      fat: 2,
      carbs: 5,
    },
  },
  {
    id: 'jeyuk_dupbap',
    name: '제육덮밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 685,
      protein: 32,
      fat: 26,
      carbs: 85,
    },
  },
  {
    id: 'ojingeo_dupbap',
    name: '오징어덮밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 595,
      protein: 28,
      fat: 18,
      carbs: 82,
    },
  },
  {
    id: 'dakgalbi_dupbap',
    name: '닭갈비덮밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 645,
      protein: 35,
      fat: 22,
      carbs: 80,
    },
  },
  {
    id: 'hangjeongsal',
    name: '항정살',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 546,
      protein: 38,
      fat: 42,
      carbs: 0,
    },
  },
  {
    id: 'jogaegui',
    name: '조개구이',
    unit: '인분',
    unitWeight: 250,
    nutrition: {
      calories: 225,
      protein: 32,
      fat: 8,
      carbs: 6,
    },
  },
  {
    id: 'jangeogui',
    name: '장어구이',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 485,
      protein: 45,
      fat: 28,
      carbs: 12,
    },
  },
  {
    id: 'galmegissal',
    name: '갈매기살',
    unit: '인분',
    unitWeight: 200,
    nutrition: {
      calories: 485,
      protein: 42,
      fat: 32,
      carbs: 0,
    },
  },
  {
    id: 'nakjibokkeum',
    name: '낙지볶음',
    unit: '인분',
    unitWeight: 300,
    nutrition: {
      calories: 285,
      protein: 35,
      fat: 10,
      carbs: 18,
    },
  },
  {
    id: 'cheonggukjang_jjigae',
    name: '청국장찌개',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 295,
      protein: 24,
      fat: 16,
      carbs: 18,
    },
  },
  {
    id: 'dongtae_jjigae',
    name: '동태찌개',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 245,
      protein: 28,
      fat: 12,
      carbs: 14,
    },
  },
  {
    id: 'yukgaejang',
    name: '육개장',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 385,
      protein: 32,
      fat: 22,
      carbs: 16,
    },
  },
  {
    id: 'maeuntang',
    name: '매운탕',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 285,
      protein: 35,
      fat: 12,
      carbs: 14,
    },
  },
  {
    id: 'dalrae_doenjangguk',
    name: '달래된장국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 125,
      protein: 8,
      fat: 6,
      carbs: 12,
    },
  },
  {
    id: 'oi_naengguk',
    name: '오이냉국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 85,
      protein: 4,
      fat: 2,
      carbs: 14,
    },
  },
  {
    id: 'gochudalgyal_guk',
    name: '고추달걀국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 145,
      protein: 10,
      fat: 8,
      carbs: 8,
    },
  },
  {
    id: 'baechu_doenjangguk',
    name: '배추된장국',
    unit: '그릇',
    unitWeight: 300,
    nutrition: {
      calories: 115,
      protein: 8,
      fat: 5,
      carbs: 12,
    },
  },
  {
    id: 'jogae_맑은국',
    name: '맑은조개국',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 145,
      protein: 18,
      fat: 4,
      carbs: 12,
    },
  },
  {
    id: 'ugeoji_guk',
    name: '우거지국',
    unit: '그릇',
    unitWeight: 350,
    nutrition: {
      calories: 165,
      protein: 12,
      fat: 8,
      carbs: 14,
    },
  },
  {
    id: 'hoe_naengmyeon',
    name: '회냉면',
    unit: '그릇',
    unitWeight: 450,
    nutrition: {
      calories: 465,
      protein: 22,
      fat: 6,
      carbs: 85,
    },
  },
  {
    id: 'janchiguksu',
    name: '잔치국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 385,
      protein: 15,
      fat: 4,
      carbs: 78,
    },
  },
  {
    id: 'bibimguksu',
    name: '비빔국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 425,
      protein: 16,
      fat: 8,
      carbs: 82,
    },
  },
  {
    id: 'tteokguk',
    name: '떡국',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 345,
      protein: 12,
      fat: 4,
      carbs: 68,
    },
  },
  {
    id: 'hotdog',
    name: '핫도그',
    unit: '개',
    unitWeight: 120,
    nutrition: {
      calories: 285,
      protein: 10,
      fat: 14,
      carbs: 32,
    },
  },
  {
    id: 'yuk_jeon',
    name: '육전',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 345,
      protein: 28,
      fat: 22,
      carbs: 12,
    },
  },
  {
    id: 'saengseon_jeon',
    name: '생선전',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 285,
      protein: 24,
      fat: 16,
      carbs: 14,
    },
  },
  {
    id: 'gul_jeon',
    name: '굴전',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 245,
      protein: 18,
      fat: 14,
      carbs: 16,
    },
  },
  {
    id: 'kkongal_jeon',
    name: '꼬막전',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 265,
      protein: 20,
      fat: 14,
      carbs: 18,
    },
  },
  {
    id: 'tuikim',
    name: '튀김',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 485,
      protein: 16,
      fat: 32,
      carbs: 42,
    },
  },

  {
    id: 'bulgogi_dupbap',
    name: '불고기덮밥',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 625,
      protein: 28,
      fat: 18,
      carbs: 92,
    },
  },
  {
    id: 'geotjeori',
    name: '겉절이',
    unit: '접시',
    unitWeight: 100,
    nutrition: {
      calories: 35,
      protein: 2,
      fat: 1,
      carbs: 6,
    },
  },
  {
    id: 'goguma_jorim',
    name: '고구마조림',
    unit: '접시',
    unitWeight: 150,
    nutrition: {
      calories: 185,
      protein: 2,
      fat: 0.5,
      carbs: 44,
    },
  },
  {
    id: 'myeolchi_bokkeum',
    name: '멸치볶음',
    unit: '접시',
    unitWeight: 50,
    nutrition: {
      calories: 145,
      protein: 18,
      fat: 6,
      carbs: 4,
    },
  },
  {
    id: 'dongchimi_guksu',
    name: '동치미국수',
    unit: '그릇',
    unitWeight: 400,
    nutrition: {
      calories: 345,
      protein: 12,
      fat: 2,
      carbs: 72,
    },
  },
  {
    id: 'ojingeo_sundae',
    name: '오징어순대',
    unit: '접시',
    unitWeight: 200,
    nutrition: {
      calories: 265,
      protein: 24,
      fat: 8,
      carbs: 32,
    },
  },
  {
    id: 'modeumjeon',
    name: '모듬전',
    unit: '접시',
    unitWeight: 300,
    nutrition: {
      calories: 485,
      protein: 22,
      fat: 28,
      carbs: 42,
    },
  },
];
// 검색을 위해 두 배열을 합침
export const foodDatabase = [...ingredientDatabase, ...completedFoodDatabase];
